FROM node:16-alpine
RUN mkdir -p /app
ENV BOT_SERVICE_URL=$BOT_SERVICE_URL \
    BOT_API_TOKEN=$BOT_API_TOKEN \
    PORT=$PORT \
    REDIS_HOST=$REDIS_HOST \
    REDIS_PORT=$REDIS_PORT \
    REDIS_INDEX=$REDIS_INDEX \
    WHATSAPP_VERSION=$WHATSAPP_VERSION \
    WHATSAPP_PHONEID=$WHATSAPP_PHONEID \
    WHATSAPP_TOKEN=$WHATSAPP_TOKEN \
    VERIFY_TOKEN=$VERIFY_TOKEN \
    CHAR_LIMIT=$CHAR_LIMIT \
    WA_PROVIDER_TOKEN=$WA_PROVIDER_TOKEN \
    TELEMETRY_SERVICE_URL=$TELEMETRY_SERVICE_URL \
    API_TOKEN=$API_TOKEN \
    APP_ENV=$APP_ENV \
    APP_NAME=$APP_NAME
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN rm -rf .env.local
EXPOSE 3010
CMD [ "npm" , "start"]
